name: Build and Deploy to Azure Static Web App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      # 1. Hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js para usar la versión compatible con Angular (v20.19 o v22.12)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19'  # o usa '22.12' según tu preferencia

      # 3. Instalar las dependencias de Node.js
      - name: Install dependencies
        run: npm install

      # 4. Construir la aplicación
      - name: Build the app
        run: npm run build

      # 5. Desplegar en Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FLOWER_0C7131C0F }}
          app_location: "/"  # Ruta de tu aplicación
          output_location: "dist/app-multi_acueductos/browser"  # Ajusta según tu carpeta de salida generada por Angular
