name: Deploy to TEST - app-aqua-plus-web-test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  APP_NAME: app-aqua-plus-web-test
  RESOURCE_GROUP: rg_code_makers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular SSR
        run: npm run build

      - name: Verify build
        run: ls -la dist/aqua-plus

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D6AF461FA5C24F4B9F68A0A6680B2F04 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E64924ECF3504939A52FF7004FE59CAA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04E4B3D9D34842DEB8A0B3BEC2453A34 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          package: dist/aqua-plus

      - name: Restart App Service
        run: |
          az webapp restart \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP
